from random import randint
DEUDA_TOTAL = randint(9500,16500)
PROBABILIDAD_EVENTO = 0.15
PORCENTAJE_APUESTA_TACANO = 70
BONIFICACION_TACANO = 750
BONIFICACION_SUERTE_CASUAL = 3
BONIFICACION_BEBEDOR = 2
FRUSTRACION_PERDER = 1
CONFIANZA_PERDER = 1
EGO_GANAR = 2
CARISMA_GANAR = 1
FRUSTRACION_GANAR = 2
MIN_ENERGIA_BEBESTIBLE = 2
MAX_ENERGIA_BEBESTIBLE = 12
DINERO_SHOW = 90
ENERGIA_SHOW = 10
FRUSTRACION_SHOW = 6
